package com.asemi.ailab.agent_seminar;

/**
 * Created by wataru on 17/02/17.
 */

//public enum CardInformation {
//}

enum Side {
    KDR, FRS, MOF
}
enum Color {
    RED, BLUE, BLACK
}
enum SendMethod {
    SECRECY, CONFIDENTIAL, RELEASE
}
enum Strategy{
    LOCKON, DISTRIBUTE, INTERCEPT, DECODE, COUNTERACT, TRAP/*誤導*/, PROVE, DELETE, TRANSFER
}
enum Lockon {
    LOCKON, LOST, NORMAL
}
enum AgentAttribute {
    SECRET, PUBLIC, NOMAL
}
enum AbilityEffect {
    RESIDENT, MOMENT
}
enum Gender {
    MALE, FEMALE, NONE
}
enum AgentName {
    THE_SPEAKER, TANK, OBLIQUE_SHADOW, TITANIUM, LARK_LADY, SWAN_MAIDEN, HUNTLESS,
    BLACKHAND, NIGHTMARE, BARON_BRUMEL, MARK_JR, STATIC_ELECTRICITY, VIPER, ANGEL,
    SAVAGE_ASSASSIN, DOUBLE_KNIGHT, KWANG_KIK, DARK_FLOW, DIAMONDMAN, PERFUME, TOUGH_GUN,
    RED_BLADE, ALIAS, BACK_FIRE, TRINITY, J, THE_DETECTIVE

    /* CHAINER, PSYCHOPATH, GOLD_HEAD, NEUTRAL, GAME_MASTER, DUELIST, HAND_STANDER,  *
     * SMALL_SPACE, FILLER, MOMENT_SLEEP, BITARITY_RECORDER, CHAIRMAN, AMNESIA,      *
     * TIPSY, PEPPER, JUGGLER, KUROSAWA_SENSEI, LIFEGAMER, SUNFLOWER, FISHCAKE       */
}

enum Phase {
    START, FILL, STRATEGY, SEND, FINISH
}